const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu?.addEventListener('click',()=>{nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='82px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px';nav.style.background='#111318';nav.style.flexDirection='column';nav.style.alignItems='flex-start'});
const footer=document.querySelector('footer');if(footer&&!footer.querySelector('.facebook-link')){const a=document.createElement('a');a.className='social-link facebook-link';a.href='https://www.facebook.com/powerdancestudiogandia/';a.target='_blank';a.rel='noopener';a.textContent='FACEBOOK ↗';footer.appendChild(a)}
const heroImage=document.querySelector('.hero-image img');if(heroImage)heroImage.src='assets/hero-modern.png';
const contactSection=document.querySelector('#contacto');if(contactSection&&!document.querySelector('#precios')){const prices=document.createElement('section');prices.id='precios';prices.className='section pricing';prices.innerHTML='<div class="section-heading"><div><div class="section-tag">03 / PRECIOS</div><h2>Elige tu<br><em>ritmo.</em></h2></div><p>Opciones pensadas para que encuentres la forma de bailar que mejor encaja contigo.</p></div><div class="price-grid"><article><span class="num">01</span><h3>1 CLASE</h3><strong>CONSULTAR</strong><p>Perfecta para probar una disciplina y descubrir tu estilo.</p><a href="#contacto">Preguntar →</a></article><article class="featured"><span class="num">02</span><h3>PACK MENSUAL</h3><strong>CONSULTAR</strong><p>Entrena con continuidad y forma parte de la comunidad Power.</p><a href="#contacto">Reservar →</a></article><article><span class="num">03</span><h3>COMBO</h3><strong>CONSULTAR</strong><p>Combina estilos y lleva tu evolución un paso más allá.</p><a href="#contacto">Preguntar →</a></article></div>';contactSection.parentNode.insertBefore(prices,contactSection)}if(!document.querySelector('.whatsapp-float')){const wa=document.createElement('a');wa.className='whatsapp-float';wa.href='https://wa.me/34647067659?text=Hola%20Power%20Dance%20Studio%2C%20quiero%20informaci%C3%B3n%20sobre%20las%20clases';wa.target='_blank';wa.rel='noopener';wa.setAttribute('aria-label','Contactar por WhatsApp');wa.innerHTML='<span>☏</span><b>WHATSAPP</b>';document.body.appendChild(wa)}
const heroImg=document.querySelector('.hero-image img');if(heroImg){const video=document.createElement('video');video.className='hero-video';video.src='assets/hero-dance.mp4';video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;video.setAttribute('aria-label','Vídeo de Power Dance Studio');heroImg.replaceWith(video)}
const brandLogo=document.querySelector('.brand img');if(brandLogo)brandLogo.src='https://raw.githubusercontent.com/danielaalzate/powerdance/main/assets/logo-clean.png';
const instagramLink=document.querySelector('footer .social-link');if(instagramLink){instagramLink.classList.add('instagram-icon');instagramLink.setAttribute('aria-label','Instagram de Power Dance Studio');instagramLink.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.7" r="1" fill="currentColor" stroke="none"/></svg>'}
const whatsappButton=document.querySelector('.whatsapp-float');if(whatsappButton){whatsappButton.setAttribute('aria-label','Contactar por WhatsApp');whatsappButton.innerHTML='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M27.1 4.8A15.7 15.7 0 0 0 2.8 23.7L1 31l7.5-1.9A15.7 15.7 0 1 0 27.1 4.8ZM16 28.6c-2.4 0-4.7-.6-6.8-1.8l-.5-.3-4.4 1.1 1.2-4.3-.3-.5A12.6 12.6 0 1 1 16 28.6Zm6.9-9.4c-.4-.2-2.5-1.2-2.9-1.3-.4-.2-.6-.2-.9.2s-1.1 1.3-1.3 1.6c-.2.3-.5.3-.9.1a10.3 10.3 0 0 1-3-1.9 11.4 11.4 0 0 1-2.1-2.6c-.2-.4 0-.6.1-.8l.6-.7.3-.6c.1-.2 0-.5-.1-.7l-1.3-3.1c-.3-.7-.7-.6-.9-.6h-.8c-.3 0-.7.1-1 .5s-1.4 1.4-1.4 3.5 1.5 4.1 1.7 4.4c.2.3 3 4.7 7.4 6.5 1 .4 1.8.7 2.4.9 1 .3 2 .3 2.7.2.8-.1 2.5-1 2.8-2 .4-1 .4-1.9.3-2.1-.1-.2-.4-.3-.8-.5Z" fill="currentColor"/></svg>'}

