const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu?.addEventListener('click',()=>{nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='absolute';nav.style.top='82px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px';nav.style.background='#111318';nav.style.flexDirection='column';nav.style.alignItems='flex-start'});
const footer=document.querySelector('footer');if(footer&&!footer.querySelector('.facebook-link')){const a=document.createElement('a');a.className='social-link facebook-link instagram-icon';a.href='https://www.facebook.com/powerdancestudiogandia/';a.target='_blank';a.rel='noopener';a.setAttribute('aria-label','Facebook de Power Dance Studio');a.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M14 8h3V4h-3c-3.3 0-5 1.9-5 5v3H6v4h3v8h4v-8h3.3l.7-4H13V9c0-.7.3-1 1-1Z"/></svg>';footer.appendChild(a)}
const heroImage=document.querySelector('.hero-image img');if(heroImage)heroImage.src='assets/hero-modern.png';
const contactSection=document.querySelector('#contacto');if(contactSection&&!document.querySelector('#precios')){const prices=document.createElement('section');prices.id='precios';prices.className='section pricing';prices.innerHTML='<div class="section-heading"><div><div class="section-tag">03 / PRECIOS</div><h2>Elige tu<br><em>ritmo.</em></h2></div><p>Opciones pensadas para que encuentres la forma de bailar que mejor encaja contigo.</p></div><div class="price-grid"><article><span class="num">01</span><h3>1 CLASE</h3><strong>CONSULTAR</strong><p>Perfecta para probar una disciplina y descubrir tu estilo.</p><a href="#contacto">Preguntar →</a></article><article class="featured"><span class="num">02</span><h3>PACK MENSUAL</h3><strong>CONSULTAR</strong><p>Entrena con continuidad y forma parte de la comunidad Power.</p><a href="#contacto">Reservar →</a></article><article><span class="num">03</span><h3>COMBO</h3><strong>CONSULTAR</strong><p>Combina estilos y lleva tu evolución un paso más allá.</p><a href="#contacto">Preguntar →</a></article></div>';contactSection.parentNode.insertBefore(prices,contactSection)}if(!document.querySelector('.whatsapp-float')){const wa=document.createElement('a');wa.className='whatsapp-float';wa.href='https://wa.me/34647067659?text=Hola%20Power%20Dance%20Studio%2C%20quiero%20informaci%C3%B3n%20sobre%20las%20clases';wa.target='_blank';wa.rel='noopener';wa.setAttribute('aria-label','Contactar por WhatsApp');wa.innerHTML='<span>☏</span><b>WHATSAPP</b>';document.body.appendChild(wa)}
const heroImg=document.querySelector('.hero-image img');if(heroImg){const video=document.createElement('video');video.className='hero-video';video.src='assets/hero-dance.mp4';video.poster='assets/hero-modern.png';video.preload='auto';video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;video.setAttribute('aria-label','Vídeo de Power Dance Studio');heroImg.replaceWith(video)}
const brandLogo=document.querySelector('.brand img');if(brandLogo)brandLogo.src='https://raw.githubusercontent.com/danielaalzate/powerdance/main/assets/logo-clean.png';
const instagramLink=document.querySelector('footer .social-link');if(instagramLink){instagramLink.classList.add('instagram-icon');instagramLink.setAttribute('aria-label','Instagram de Power Dance Studio');instagramLink.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.7" r="1" fill="currentColor" stroke="none"/></svg>'}
const whatsappButton=document.querySelector('.whatsapp-float');if(whatsappButton){whatsappButton.setAttribute('aria-label','Contactar por WhatsApp');whatsappButton.innerHTML='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M27.1 4.8A15.7 15.7 0 0 0 2.8 23.7L1 31l7.5-1.9A15.7 15.7 0 1 0 27.1 4.8ZM16 28.6c-2.4 0-4.7-.6-6.8-1.8l-.5-.3-4.4 1.1 1.2-4.3-.3-.5A12.6 12.6 0 1 1 16 28.6Zm6.9-9.4c-.4-.2-2.5-1.2-2.9-1.3-.4-.2-.6-.2-.9.2s-1.1 1.3-1.3 1.6c-.2.3-.5.3-.9.1a10.3 10.3 0 0 1-3-1.9 11.4 11.4 0 0 1-2.1-2.6c-.2-.4 0-.6.1-.8l.6-.7.3-.6c.1-.2 0-.5-.1-.7l-1.3-3.1c-.3-.7-.7-.6-.9-.6h-.8c-.3 0-.7.1-1 .5s-1.4 1.4-1.4 3.5 1.5 4.1 1.7 4.4c.2.3 3 4.7 7.4 6.5 1 .4 1.8.7 2.4.9 1 .3 2 .3 2.7.2.8-.1 2.5-1 2.8-2 .4-1 .4-1.9.3-2.1-.1-.2-.4-.3-.8-.5Z" fill="currentColor"/></svg>'}
const scheduleSection=document.querySelector('#horarios');if(scheduleSection&&!document.querySelector('#equipo')){const team=document.createElement('section');team.id='equipo';team.className='section team';team.innerHTML='<div class="section-heading"><div><div class="section-tag">03 / EQUIPO POWER</div><h2>El talento<br><em>que te impulsa.</em></h2></div><p>Profesionales que convierten la técnica, la energía y la confianza en movimiento.</p></div><div class="team-grid"><article class="team-card"><img src="assets/equipo-carmen.png" alt="Carmen García, profesora de Power Dance Studio"><div><span class="num">KIDS 1 · KIDS 2</span><h3>CARMEN<br>GARCÍA</h3><p>Guiando los primeros pasos con energía, técnica y confianza.</p></div></article><article class="team-card"><img src="assets/equipo-andrea.png" alt="Andrea Gregori, profesora de Power Dance Studio"><div><span class="num">HEELS · COMMERCIAL · KIDS 3</span><h3>ANDREA<br>GREGORI</h3><p>Actitud, presencia y movimiento para brillar en cada clase.</p></div></article></div>';scheduleSection.parentNode.insertBefore(team,scheduleSection)}
const carmenCopy=document.querySelector('#equipo .team-card:first-child p');if(carmenCopy)carmenCopy.textContent='Clases de danza urbana para Kids 1 y Kids 2, trabajando Comercial, Hip Hop y House.';
const ornamentLayer=document.createElement('div');ornamentLayer.className='scroll-ornaments';ornamentLayer.setAttribute('aria-hidden','true');ornamentLayer.innerHTML='<span class="orbit"></span><span class="beam"></span><span class="tick"></span>';document.body.appendChild(ornamentLayer);
const revealItems=document.querySelectorAll('.section-heading,.intro>div:last-child,.class-grid article,.team-card,.table-wrap,.gallery-grid img,.contact>h2,.contact>p,.contact>.button');revealItems.forEach((item,index)=>{item.classList.add('scroll-reveal');item.style.transitionDelay=`${Math.min(index%4,3)*80}ms`});const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('is-visible')}),{threshold:.12});revealItems.forEach(item=>revealObserver.observe(item));
let scrollFrame;window.addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{const y=window.scrollY;document.documentElement.style.setProperty('--scroll-y',y);document.querySelectorAll('.section').forEach((section,index)=>{const distance=section.getBoundingClientRect().top-window.innerHeight/2;section.style.setProperty('--parallax',distance*.045);section.style.setProperty('--rotation',`${(y*.012+index*7)%18-9}deg`)});scrollFrame=null})},{passive:true});window.dispatchEvent(new Event('scroll'));

